{
	"_Type": "Action.Type.CheckRequiredFields",
	"ActionResult": {
		"_Name": "chek_validarpedido"
	},
	"OnSuccess": "/Skycm_v3/Rules/consultas/ValidarConsultaSociedad.js",
	"RequiredFields": [
		"fc_nopedido"
	]
}