{
	"_Type": "Action.Type.Navigation",
	"ActionResult": {
		"_Name": "nav_MainPage"
	},
	"PageToOpen": "/Skycm_v3/Pages/Main.page",
	"BackStackVisible": true,
	"ClearHistory": true,
	"NavigationType": "Inner",
	"Transition": {
		"Curve": "Linear",
		"Name": "Fade"
	}
}