{
	"_Type": "Action.Type.RestService.SendRequest",
	"ActionResult": {
		"_Name": "ResultRest"
	},
	"OnFailure": "/Skycm_v3/Actions/Consultas/rest/ErrorPedido.action",
	"OnSuccess": "/Skycm_v3/Rules/consultas/afs/RestPedidos3.js",
	"ShowActivityIndicator": true,
	"ActivityIndicatorText": "Realizando consulta....",
	"Target": {
		"Service": "/Skycm_v3/Services/Rest_Inventario.service",
		"Path": "/PedVendedor/rest",
		"OutputPath": "/T_PedidoVendMovilResp/T_Cabecera",
		"RequestProperties": {
			"Method": "PUT",
			"Body": {
				"T_PED_VEND_MOVIL": {
					"PEDIDO": "#Page:ConsultaPedido/#Control:fc_nopedido/#Value",
					"VENDEDOR": "#Page:ConsultaPedido/#Control:fc_pernr/#Value"
				}
			},
			"Headers": {
				"Content-Type": "application/json"
			}
		}
	}
}