{
	"_Type": "Action.Type.Message",
	"ActionResult": {
		"_Name": "msj_errorcerrarvisita"
	},
	"Message": "#ActionResults:TerminarVisitaActiva/error",
	"Title": "Error al cerrar la visita",
	"OKCaption": "Ok"
}