{
	"_Type": "Action.Type.ODataService.UpdateEntity",
	"ActionResult": {
		"_Name": "create_Jornada"
	},
	"OnFailure": "/Skycm_v3/Actions/Visitas/msj_errorJornadaLaboral.action",
	"OnSuccess": "/Skycm_v3/Actions/JornadaLaboral/close_modal_jornada.action",
	"ShowActivityIndicator": true,
	"ActivityIndicatorText": "Finalizando Jornada laboral...",
	"Target": {
		"Service": "/Skycm_v3/Services/Dest_SkyCM_Productivo.service",
		"EntitySet": "WORKDAY",
		"ReadLink": "{@odata.readLink}"
	},
	"Properties": {
		"ID_JORNADA": "#Page:DetalleJornadaLaboral/#Control:FC_IDJORDETALLE/#Value",
		"PERNR": "#Page:DetalleJornadaLaboral/#Control:FCDURACIONJOR/#Value",
		"HORA_FIN": "#Page:DetalleJornadaLaboral/#Control:FC_HORAFINJOR/#Value",
		"ESTADO": "INACTIVO"
	}
}