{
	"_Type": "Action.Type.ClosePage",
	"ActionResult": {
		"_Name": "close_modal_jornada"
	},
	"OnSuccess": "/Skycm_v3/Actions/JornadaLaboral/msj_jornada_finalizada.action",
	"DismissModal": "Action.Type.ClosePage.Completed",
	"CancelPendingActions": false,
	"NavigateBackToPage": "Main"
}