{
	"_Type": "Action.Type.ClosePage",
	"ActionResult": {
		"_Name": "close_modal_jornada"
	},
	"OnSuccess": "/Skycm_v3/Actions/Service/UploadOnly.action",
	"CancelPendingActions": false,
	"NavigateBackToPage": "Main"
}