{
	"_Type": "Action.Type.BannerMessage",
	"ActionResult": {
		"_Name": "msj_JornadaFinalizada"
	},
	"OnSuccess": "/Skycm_v3/Actions/JornadaLaboral/close_modal_jornada.action",
	"Message": "Jornada finalizada con exito!!!",
	"Duration": 60,
	"Animated": true
}