{
	"_Type": "Action.Type.BannerMessage",
	"ActionResult": {
		"_Name": "msj_jornada_finalizada"
	},
	"OnSuccess": "/Skycm_v3/Actions/Application/nav_MainPage.action",
	"Message": "Jornada Finalizada con exito!!!",
	"Duration": 100,
	"Animated": true,
	"Semantic": "Positive"
}