{
	"_Type": "Action.Type.Message",
	"ActionResult": {
		"_Name": "msj_JornadaLaboralActiva"
	},
	"Message": "ya tienes una jornada laboral activa...",
	"Title": "Jornada activa!!!",
	"OKCaption": "Ok"
}