{
	"_Type": "Action.Type.Navigation",
	"ActionResult": {
		"_Name": "nav_InicioJornadaLaboral"
	},
	"PageToOpen": "/Skycm_v3/Pages/Jornadalaboral/InicioJornadalaboral.page",
	"BackStackVisible": true,
	"OuterNavigation": true,
	"NavigationType": "Inner"
}